# Generated by Django 3.2.8 on 2021-10-13 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('expected_end_date', models.DateTimeField(blank=True, null=True)),
                ('git_link', models.URLField(blank=True, null=True)),
                ('drive_folder_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('expected_hours', models.FloatField()),
                ('actual_hours', models.FloatField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='project_detail.project')),
                ('tags', models.ManyToManyField(to='project_detail.Tag')),
            ],
        ),
    ]
