# Generated by Django 3.2.8 on 2021-10-16 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_detail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='actual_hours',
            field=models.FloatField(default=0),
        ),
    ]
