# Generated by Django 3.2.8 on 2021-10-18 01:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project_detail', '0002_alter_task_actual_hours'),
    ]

    operations = [
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=160, null=True)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OP', 'Open'), ('FI', 'Finish'), ('SK', 'Skip'), ('AB', 'Abort')], default='OP', max_length=2)),
                ('comment', models.TextField(blank=True, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='project_detail.task')),
            ],
        ),
    ]
