# Generated by Django 3.2.8 on 2021-10-18 01:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project_detail', '0003_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='commits',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='pull_requests',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='step',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
