# Generated by Django 3.2.8 on 2021-10-24 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_detail', '0004_auto_20211018_0710'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('OP', 'Open'), ('FI', 'Finish'), ('SK', 'Skip'), ('AB', 'Abort')], default='OP', max_length=2),
        ),
    ]
